version: '3'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes: 
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf

  www: 
    user: 1000:1000
    build:
      context: ./www
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./www/src/
        target: /usr/share/nginx/html/


